### ISSUE TITLE
Biogeochemical GPS issue

### ISSUE THREAD

**Issue by Stephen-Lail** [COAST-Lab/Biogeochemical-Drifter#1]
In the code for the GPS location, C++ requires the library SDFat to function. When the library is called, the library itself has 11 yellow labeled problems that range from unused variable to unaligned pointer values. I can bypass the remaining 3 in the drifter code if needed by using the line UNUSED or (void) but that will cause issues further down the line. I believe this to be an issue caused by the particle update and the libraries themselves haven't been updated yet so the issue could resolve itself in a few weeks assuming the library is updated to the new version.

**Comment by SUPScientist** [comment]
See https://github.com/COAST-Lab/Biogeochemical-Drifter/issues/2 and post again here when you've updated the repository following the template or related structure that meets your needs.

**Comment by SUPScientist** [comment]
#2 solved as requested with https://github.com/COAST-Lab/Biogeochemical-Drifter/commit/3fea92a403a32fbd44a8e681b24f92b83af3ba44. This issue status is unknown.
