### ISSUE TITLE
Clean up repeated declarations

### ISSUE THREAD

**Issue by SUPScientist** [COAST-Lab/Biogeochemical-Drifter#11]
Repeated code here should be cleaned up:

https://github.com/COAST-Lab/Biogeochemical-Drifter/blob/0846e766e49fa8ac66b0f89e48320029c7e35019/Firmware/Drifter_Code_V2/src/Drifter_Code_V2.cpp#L53-L68

**Comment by Stephen-Lail** [comment]
Cleaned up the multiple void step() statements
